import { FunctionComponent } from "react";
import styles from "./TV1.module.css";

const TV1: FunctionComponent = () => {
  return (
    <div className={styles.tV1}>
      <img
        className={styles.pptPdfpdfPage1Of51}
        alt=""
        src="../ppt-pdfpdf--page-1-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage2Of51}
        alt=""
        src="../ppt-pdfpdf--page-2-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage3Of51}
        alt=""
        src="../ppt-pdfpdf--page-3-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage5Of51}
        alt=""
        src="../ppt-pdfpdf--page-5-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage6Of51}
        alt=""
        src="../ppt-pdfpdf--page-6-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage7Of51}
        alt=""
        src="../ppt-pdfpdf--page-7-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage8Of51}
        alt=""
        src="../ppt-pdfpdf--page-8-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage9Of51}
        alt=""
        src="../ppt-pdfpdf--page-9-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage10Of51}
        alt=""
        src="../ppt-pdfpdf--page-10-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage11Of51}
        alt=""
        src="../ppt-pdfpdf--page-11-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage12Of51}
        alt=""
        src="../ppt-pdfpdf--page-12-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage13Of51}
        alt=""
        src="../ppt-pdfpdf--page-13-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage14Of51}
        alt=""
        src="../ppt-pdfpdf--page-14-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage15Of51}
        alt=""
        src="../ppt-pdfpdf--page-15-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage17Of51}
        alt=""
        src="../ppt-pdfpdf--page-17-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage18Of51}
        alt=""
        src="../ppt-pdfpdf--page-18-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage19Of51}
        alt=""
        src="../ppt-pdfpdf--page-19-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage20Of51}
        alt=""
        src="../ppt-pdfpdf--page-20-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage21Of51}
        alt=""
        src="../ppt-pdfpdf--page-21-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage22Of51}
        alt=""
        src="../ppt-pdfpdf--page-22-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage23Of51}
        alt=""
        src="../ppt-pdfpdf--page-23-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage25Of51}
        alt=""
        src="../ppt-pdfpdf--page-25-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage26Of51}
        alt=""
        src="../ppt-pdfpdf--page-26-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage27Of51}
        alt=""
        src="../ppt-pdfpdf--page-27-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage28Of51}
        alt=""
        src="../ppt-pdfpdf--page-28-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage33Of51}
        alt=""
        src="../ppt-pdfpdf--page-33-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage35Of51}
        alt=""
        src="../ppt-pdfpdf--page-35-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage36Of51}
        alt=""
        src="../ppt-pdfpdf--page-36-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage37Of51}
        alt=""
        src="../ppt-pdfpdf--page-37-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage39Of51}
        alt=""
        src="../ppt-pdfpdf--page-39-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage40Of51}
        alt=""
        src="../ppt-pdfpdf--page-40-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage41Of51}
        alt=""
        src="../ppt-pdfpdf--page-41-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage42Of51}
        alt=""
        src="../ppt-pdfpdf--page-42-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage43Of51}
        alt=""
        src="../ppt-pdfpdf--page-43-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage44Of51}
        alt=""
        src="../ppt-pdfpdf--page-44-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage45Of51}
        alt=""
        src="../ppt-pdfpdf--page-45-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage47Of51}
        alt=""
        src="../ppt-pdfpdf--page-47-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage48Of51}
        alt=""
        src="../ppt-pdfpdf--page-48-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage49Of51}
        alt=""
        src="../ppt-pdfpdf--page-49-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage50Of51}
        alt=""
        src="../ppt-pdfpdf--page-50-of-511@2x.png"
      />
      <img
        className={styles.pptPdfpdfPage51Of51}
        alt=""
        src="../ppt-pdfpdf--page-51-of-511@2x.png"
      />
    </div>
  );
};

export default TV1;
